# travisci config
env:
  global:
  - CLOUD_IN_A_BOX_PROJECT=true

os: linux
dist: focal

jobs:
  fast_finish: true
  include:
  # JOB: CiaB vanilla on focal
  - env:
      - PRIMARY_HOSTNAME=box1.abc.com
      - DOWNLOAD_NEXTCLOUD_FROM_GITHUB=true
    language: shell
    os: linux
    dist: focal
    name: vanilla-focal
    install:
      - sudo tests/system-setup/vanilla.sh -v
    script:
      # launch automated tests
      - sudo tests/runner.sh -dumpoutput default
