# travisci config
env:
  global:
  - CLOUD_IN_A_BOX_PROJECT=true

jobs:
  fast_finish: true
  include:
  # JOB: CiaB vanilla on bionic
  - env:
      - PRIMARY_HOSTNAME=box1.abc.com
    language: shell
    os: linux
    dist: bionic
    name: vanilla-bionic
    services:
      - redis-server
    install:
      - sudo tests/system-setup/vanilla.sh -v
    script:
      # launch automated tests
      - sudo tests/runner.sh -dumpoutput default

