load './funcs.rb'

Vagrant.configure("2") do |config|

  config.vm.synced_folder "../..", "/cloudinabox", id: "cloudinabox", automount: false
  testing = Testing.new
  testing.say_groups

  #
  # vanilla with ubuntu 20 (focal), then upgrade to ubuntu 22 (jammy)
  # requires plugin 'vagrant-reload'
  #

  if testing.group('relupgrade')
    config.vm.define "vanilla-focal2jammy" do |m1|
      if !Vagrant.has_plugin?('vagrant-reload')
        raise("Plugin 'vagrant-reload' is required")
      end
    
      use_preloaded_box m1, "ubuntu/focal64"
      m1.vm.provision :shell, :inline => <<-SH
cd /cloudinabox
source tests/vagrant/globals.sh || exit 1
export PRIMARY_HOSTNAME=f2j1.abc.com
export SKIP_SYSTEM_UPDATE=0
tests/system-setup/vanilla.sh -v || exit 1
tests/runner.sh default || exit 2
SH

      # reboot may be required when updates were applied
      m1.vm.boot_timeout = 600
      m1.vm.provision :reload

      # upgrade ubuntu
      m1.vm.provision :shell, :inline => <<-SH
cd /cloudinabox
tests/bin/wait_for_network.sh
tests/bin/do_release_upgrade.sh || exit 3
SH

      # reboot required after any system upgrade
      m1.vm.provision :reload

      m1.vm.provision :shell, :inline => <<-SH
cd /cloudinabox
source tests/system-setup/setup-defaults.sh
setup/start.sh -v || exit 4
tests/runner.sh default || exit 5
SH
    end
  end
  
  
  #
  # vanilla with encryption-at-rest / focal
  #
  
  config.vm.define "vanilla-ehdd-focal" do |m1|
    use_preloaded_box m1, "ubuntu/jammy64"    
    m1.vm.provision :shell, :inline => <<-SH
cd /cloudinabox
source tests/vagrant/globals.sh || exit 1
export PRIMARY_HOSTNAME=qa2.abc.com
export EHDD_KEYFILE=$HOME/keyfile
echo -n "boo" >$EHDD_KEYFILE
tests/system-setup/vanilla.sh || exit 1
tests/runner.sh default || exit 2
SH
  end

  #
  # from-backup: restore a backup, then install w/focal
  #

  config.vm.define "from-backup-focal" do |m1|
    use_preloaded_box m1, "ubuntu/focal64"
    m1.vm.provision :shell, :inline => <<-SH
cd /cloudinabox
source tests/vagrant/globals.sh || exit 1
export PRIMARY_HOSTNAME=qacloud.int.com
tests/system-setup/from-backup.sh || exit 1
tests/runner.sh default || exit 2
SH
  end

end
