Vagrant.configure("2") do |config|

  config.vm.synced_folder "../../..", "/cloudinabox", id: "cloudinabox", automount: false
  config.vm.provision "file", source:"../globals.sh", destination:"globals.sh"
  config.vm.network "public_network"

  # vanilla install

  config.vm.define "vanilla" do |m1|
    m1.vm.box = "ubuntu/bionic64"
    m1.vm.provision :shell, :inline => <<-SH
source globals.sh || exit 1
export PRIMARY_HOSTNAME=vanilla.local
cd /cloudinabox
tests/system-setup/vanilla.sh; rc=$?
echo "EXITCODE: $rc"
SH
  end


end
