load '../funcs.rb'

Vagrant.configure("2") do |config|

  config.vm.synced_folder "../../..", "/cloudinabox", id: "cloudinabox", automount: false
  config.vm.network "public_network", bridge: "#$default_network_interface"
  use_preloaded_box config, "ubuntu/noble64", ".."

  if ENV['tests']=='miab'

    # vanilla connected to miab (miab-ldap with hostname "vanilla.local"
    # must be up and running)

    config.vm.define "vanilla" do |m1|
      m1.vm.provision :shell, :inline => <<-SH
cd /cloudinabox
export PRIMARY_HOSTNAME=vanilla-ciab.local
export MAILINABOX_HOST=vanilla.local
export MAILINABOX_SERVICE_PASSWORD=Test_LDAP_1234
export MAILINABOX_SMARTHOST_AUTH_USER=qa@abc.com
export MAILINABOX_SMARTHOST_AUTH_PASSWORD=Test_1234
tests/system-setup/vanilla.sh -v --qa-ca; rc=$?  # --enable-mod=coturn
echo "EXITCODE: $rc"
exit $rc
SH
    end

  else

    # vanilla (default)
    
    config.vm.define "vanilla" do |m1|
      m1.vm.provision :shell, :inline => <<-SH
cd /cloudinabox
export PRIMARY_HOSTNAME=vanilla-ciab.local
#export REQUIRED_NC_FOR_FRESH_INSTALLS=24.0.0rc3
tests/system-setup/vanilla.sh -v; rc=$?  # --enable-mod=coturn
echo "EXITCODE: $rc"
SH
    end

  end


end
