#!/bin/bash

. /etc/cloudinabox.conf  || die "Could not load /etc/cloudinabox.conf"
. setup/functions.sh     || exit 1

php="$REQUIRED_PHP_PACKAGE"
phpver="$REQUIRED_PHP_VERSION"


run_miab_web_sh() {
    # this mail-in-a-box script sets up and installs nginx and php-fpm
    # however to support our desired version of php, we must modify it
    # first
    echo "# GENERATED FILE - DO NOT EDIT - GENERATED BY setup/nginx.sh" > setup/web-miab-mods.sh \
        || die "Could not create setup/web-miab-mods.sh"

    cat setup/web-miab.sh >> setup/web-miab-mods.sh \
        || die "Could not copy setup/web-miab.sh"
    
    # don't restart any services -- we'll restart in this script
    sed -i 's/^restart_service .*/#\0/g' setup/web-miab-mods.sh || die "$errmsg"

    # run the modified script
    source_miab_script "setup/web-miab-mods.sh"


    # change the php-fpm www.conf settings that were just applied.
    # our needs are different from miab since Nextcloud is the primary
    # application here. plus, we have fewer things running so more
    # resources are available for it.
    TOTAL_PHYSICAL_MEM=$(head -n 1 /proc/meminfo | awk '{print $2}' || /bin/true)
    if [ $TOTAL_PHYSICAL_MEM -lt 1000000 ]
    then
        tools/editconf.py /etc/php/$phpver/fpm/pool.d/www.conf -c ';' \
                          pm=ondemand \
                          pm.max_children=8 \
                          pm.start_servers=2 \
                          pm.min_spare_servers=1 \
                          pm.max_spare_servers=3
    elif [ $TOTAL_PHYSICAL_MEM -lt 2000000 ]
    then
        tools/editconf.py /etc/php/$phpver/fpm/pool.d/www.conf -c ';' \
                          pm=dynamic \
                          pm.max_children=20 \
                          pm.start_servers=4 \
                          pm.min_spare_servers=1 \
                          pm.max_spare_servers=6
    elif [ $TOTAL_PHYSICAL_MEM -lt 3000000 ]
    then
        tools/editconf.py /etc/php/$phpver/fpm/pool.d/www.conf -c ';' \
                          pm=dynamic \
                          pm.max_children=90 \
                          pm.start_servers=6 \
                          pm.min_spare_servers=3 \
                          pm.max_spare_servers=9
    else
        tools/editconf.py /etc/php/$phpver/fpm/pool.d/www.conf -c ';' \
                          pm=dynamic \
                          pm.max_children=180 \
                          pm.start_servers=12 \
                          pm.min_spare_servers=6 \
                          pm.max_spare_servers=18
    fi

    # ... then, remove mail-related files we don't use...
    rm -f /var/lib/mailinabox/mobileconfig.xml
    rm -f /var/lib/mailinabox/mozilla-autoconfig.xml
    rm -f /var/lib/mailinabox/mta-sts.txt
}


add_mime_types() {
    cat <<EOF >/etc/nginx/conf.d/additional-mime-types.conf
# generated by cloud-in-a-box setup. do not modify. will be overwritten.
include mime.types;
types {
  # additional mime types
  application/javascript mjs;
}
EOF
}


create_main_site() {
    local server_name="$1"
    say_verbose "Creating port 80 nginx site"
    cat<<EOF > /etc/nginx/sites-available/cloudinabox
server {
    listen 80;
    listen [::]:80;
    server_name ${server_name};

	# Improve privacy: Hide version an OS information on
	# error pages and in the "Server" HTTP-Header.
	server_tokens off;

	location / {
		# Redirect using the 'return' directive and the built-in
		# variable '$request_uri' to avoid any capturing, matching
		# or evaluation of regular expressions.
		return 301 https://$server_name$request_uri;
	}

	location /.well-known/acme-challenge/ {
		# This path must be served over HTTP for ACME domain validation.
		# We map this to a special path where our TLS cert provisioning
		# tool knows to store challenge response files.
		alias $STORAGE_ROOT/ssl/lets_encrypt/webroot/.well-known/acme-challenge/;
	}
}
EOF
    [ $? -ne 0 ] && die "Unable to create nginx main site"
    
    ln -sf /etc/nginx/sites-available/cloudinabox /etc/nginx/sites-enabled/cloudinabox
    [ $? -ne 0 ] && die "Unable to enable nginx main site"
}



run_miab_web_sh
restart_service $php-fpm

add_mime_types
create_main_site "$PRIMARY_HOSTNAME"
#systemctl reload nginx
restart_service nginx
