name: commit-tests
on: [push, workflow_dispatch]
jobs:
  # CiaB vanilla on focal
  vanilla-focal:
    runs-on: ubuntu-20.04
    env:
      DOWNLOAD_NEXTCLOUD_FROM_GITHUB: true
      PRIMARY_HOSTNAME: box1.abc.com
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get remove --purge mysql* libmysql*
      - run: sudo rm -rf /etc/mysql
      - run: sudo rm -f /root/.my.cnf
      - run: rm -f .my.cnf
      - run: sudo update-alternatives --set php /usr/bin/php7.4
      - name: setup
        run: sudo -E tests/system-setup/vanilla.sh -v
      - name: test-runner
        run: sudo -E tests/runner.sh -dumpoutput default
