#!/usr/bin/perl

# Install into /etc/logwatch/scripts/logfiles/nextcloud/applydate
#
# STDIN contains nextcloud log file entries. Output to STDOUT only the
# entries for the logwatch date range (TimeFilter).

use strict;
use warnings;
use JSON;
use Try::Tiny;
use Logwatch ":dates";

my $debug = $ENV{"LOGWATCH_DEBUG"} || 0;
my $json = JSON->new;
$json->relaxed($JSON::true);
$json->allow_unknown($JSON::true);
$json->max_size(0);
my $lineno = 0;

my $SearchDate = TimeFilter("%Y-%m-%dT%H:%M:%S[+-][0-9]{2}:[0-9]{2}");

while (defined(my $line = <STDIN>)) {
    try {
        my $lineref = $json->decode($line);
        my $ts = $lineref->{'time'};  # eg: "2022-12-04T14:36:56-08:00"
        if ($ts =~ /$SearchDate/) {
            print $line;
        }
    }
    catch {
        # invalid json...ignore
        if ($debug>0) {
            chomp $line;
            print STDERR "Invalid JSON at input line $lineno: $line: $_\n";
        }
    };
    ++$lineno;
}
